[package]
name = "scheduling"
version = "0.1.0"
authors = ["i3abghany <mahmoudabdalghany@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
